package com.example.alert.model;

public interface ResponseCode {

	int USER_INFO_ERROR_CODE = 1001;

	int USER_REGISTER_ERROR_CODE = 1002;

	int RESEND_VERIFICATION_EMAIL_ERROR_CODE = 1005;

	int REGISTER_MAIL_VERIFICATION_ERROR_CODE = 1004;

	int DELETE_USER_ERROR_CODE = 1003;

	int LOGIN_ERROR_CODE = 1005;

	int LOGOUT_ERROR_CODE = 1020;

	int ACTIVE_SESSION_ERROR_CODE = 1025;

	int REMOVE_SESSION_ERROR_CODE = 1026;

	int REMOVE_ALL_SESSION_ERROR_CODE = 1027;

	int TWO_FACTOR_ADD_ERROR_CODE = 1010;

	int TWO_FACTOR_INFO_ERROR_CODE = 1024;

	int TWO_FACTOR_DEVICE_VERIFY_ERROR_CODE = 1025;

	int TWO_FACTOR_EMAIL_VERIFY_ERROR_CODE = 1018;

	int TWO_FACTOR_ACTIVATE_ERROR_CODE = 1024;

	int TWO_FACTOR_VERIFY_ERROR_CODE = 1011;

	int TWO_FACTOR_LIST_ERROR_CODE = 1013;

	int TWO_FACTOR_REMOVE_ERROR_CODE = 1022;

	int TWO_FACTOR_REMOVE_ALL_ERROR_CODE = 1013;

	int KYC_ADD_ERROR_CODE = 1016;

	int KYC_VERIFIED_ERROR_CODE = 1027;

	int KYC_UPLOAD_ERROR_CODE = 1017;

	int KYC_STATUS_ERROR_CODE = 1017;

	int KYC_INFO_ERROR_CODE = 1018;

	int KYC_MOBILE_NUMBER_OTP_ERROR_CODE = 1023;

	int KYC_OTP_VERIFY_ERROR_CODE = 1024;

	int ADMIN_USER_LIST_ERROR_CODE = 1022;
	
	int ADMIN_DELETE_ERROR_CODE = 1021;

	int ADMIN_USER_INFO_ERROR_CODE = 1023;

	int ADMIN_LIST_KYC_ERROR_CODE = 1027;

	int ADMIN_USER_ACCESS_ERROR_CODE = 1028;

	int ADMIN_USER_TWO_FA_RESET_ERROR_CODE = 1029;
	
	int ADMIN_UPDATE_ERROR_CODE = 1039;

	int PASSWORD_CHANGE_VERIFY_ERROR_CODE = 1013;

	int PASSWORD_CHANGE_ERROR_CODE = 1014;

	int PASSWORD_CHANGE_RESEND_ERROR_CODE = 1015;

	int PASSWORD_RESET_REQUEST_ERROR_CODE = 1007;

	int PASSWORD_RESET_VERIFY_ERROR_CODE = 1013;

	int PASSWORD_RESET_ERROR_CODE = 1014;

	int PASSWORD_RESET_RESEND_ERROR_CODE = 1015;

	int TENANT_ADD_ERROR_CODE = 1008;

	int TENANT_UPDATE_ERROR_CODE = 1006;

	int TENANT_GET_ALL_ERROR_CODE = 1009;

	int TENANT_DELETE_ERROR_CODE = 1012;

	int TENANT_UPLOAD_ERROR_CODE = 1019;

	int KYC_ADD_DOCUMENT_ERROR_CODE = 1030;

	int KYC_DOCUMENT_LIST_ERROR_CODE = 1031;

	int KYC_PROVIDER_ADD_ERROR_CODE = 1032;

	int KYC_PROVIDER_LIST_ERROR_CODE = 1033;

	int PAYMENT_PROVIDER_ADD_ERROR_CODE = 1034;

	int PAYMENT_PROVIDER_LIST_ERROR_CODE = 1035;

	int COUNTRY_ADD_ERROR_CODE = 1036;

	int COUNTRY_LIST_ERROR_CODE = 1037;

	int NOTIFICATION_LIST_ERROR_CODE= 1038;

	int MASTER_TYPE_LIST_ERROR_CODE=1039;
}